name: ci

on:
  pull_request: {}
  push:
    branches:
      - main

permissions: {}

jobs:
  lint:
    env:
      # Fail if `.config/mise.lock` is out of date:
      MISE_LOCKED: 1

      # Don't trust `.config/mise.lock`:
      MISE_LOCKED_VERIFY_PROVENANCE: 1

      # Ask GitHub, not mise's proxy, for attestations:
      MISE_USE_VERSIONS_HOST: 0

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install mise and the pinned tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          cache: false  # Restored tools aren't verified, so don't cache them
          version: 2026.9.13  # Sync with `.config/mise.toml`•`min_version`

      - name: Lint files against .editorconfig
        run: mise run lint:editorconfig

      - name: Lint Markdown files
        run: mise run lint:markdown

      - name: Lint TOML files
        run: mise run lint:toml

      - name: Lint web files
        run: mise run lint:web

      # New linters added to `.config/mise.toml` must be added and run here
      # individually.
      #
      # We intentionally don't run `mise run lint`, because we want to see a
      # specific named step (i.e. a specific named linter) fail if a problem is
      # detected, rather than just have a generic "lint" step fail and have to
      # scrutinise the logs to figure out which one.
